---
title: "Apuntes de clase"
---

## Método de eliminación

El método de eliminación es otra forma de resolver sistemas de ecuaciones lineales. Este método consiste en sumar o restar las ecuaciones de nuestro sistema o múltiplos de ellas con el fin de reducir el número de incógnitas y encontrar la solución. Para ello podemos seguir los siguientes pasos.

1) Escoger una variable a eliminar
2) Multiplicar una o ambas ecuaciones para que los coeficientes de la variable elegida sean iguales.
3) Sumar o restar las ecuaciones.
4) Resolver las ecuaciones resultantes.
5) Sustituir el valor de la incógnita obtenido en otra ecuación para obtener los valores restantes.

### Ejemplo

$$
\begin{align}
2x+3y &= 100 \tag{A}\\
x-2y &= -55 \tag{B} \\
\end{align}
$$

1) Multiplicamos por -2 la ecuación A y sumamos ambas ecuaciones

$$
\begin{align}
2x+3y &= 100 \\
{\color{blue}{-2}}x+{\color{blue}{4}}y &= {\color{blue}{110}} \\
\hline
0+7y &= 210
\end{align}
$$

2) Despejamos para $y$.

$$
\begin{align}
7y &= 210\\
y &= \frac{210}{7}=30
\end{align}
$$

3) Sustituimos el valor de $y$ en la ecuación B.

$$
\begin{align}
x-2(30) &= -55\\
x &= -55+60=5
\end{align}
$$

**Solución**

$$
\begin{align}
x &= 5\\
y &= 30
\end{align}
$$

## Matrices

Una matriz es un arreglo rectangular de $m$x$n$ números reales o complejos ordenados en $m$ filas horizontales y $n$ columnas verticales.

-    $i$ filas $1 \leq i \leq m$

-    $j$ columnas $1 \leq j \leq m$

$$
A = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$

Utilizando los ejemplos anteriores, podríamos expresar los sistemas de ecuaciones en sus formas matriciales de la siguiente manera y resolver:

$$
\begin{aligned}
2x+3y &= 100 \\
x-2y &= -55\\
\end{aligned}
\implies
\left[ 
\begin{array}{cc|c}
2 & 3 & 100 \\
1 & -2 & -55
\end{array} 
\right]
$$

Para resolver podemos seguir los mismos principios que en el método de eliminación, es decir:
- Las filas pueden sumarse o restarse entre sí.
- Cualquier fila se puede multiplicar por un escalar.
- Las filas se pueden cambiar de lugar

1)  Multiplicamos la fila 1 por 1/2

$$
\left[
\begin{array}{cc|c}
2 & 3 & 100 \\
1 & -2 & -55
\end{array}
\right]
\;\;\xrightarrow{F_1 \to \tfrac{1}{2}F_1}\;\;
\left[
\begin{array}{cc|c}
1 & \tfrac{3}{2} & 50 \\
1 & -2 & -55
\end{array}
\right]
$$


2)  Transformamos la fila 2 al restarla de la fila 1.

$$
\left[
\begin{array}{cc|c}
1 & \frac{3}{2} & 50 \\
1 & -2 & -55
\end{array}
\right]
\;\;\xrightarrow{F_2 = F_1-F_2}\;\;
\left[
\begin{array}{cc|c}
1 & \frac{3}{2} & 50 \\
1 & \frac{7}{2} & 105
\end{array}
\right]
$$


3)  Multiplicamos la fila 2 por su recíproco $\frac{2}{7}$

$$
\left[
\begin{array}{cc|c}
1 & \frac{3}{2} & 50 \\
1 & \frac{7}{2} & 105
\end{array}
\right]
\;\;\xrightarrow{F_2 \to \frac{2}{7}F_2}\;\;
\left[
\begin{array}{cc|c}
1 & \frac{3}{2} & 50 \\
0 & 1 & \frac{210}{7}
\end{array}
\right]
$$

4)  Transformamos la fila 1 restandole $\frac{3}{2}$ de la fila 2 $F_1-\frac{3}{2}F_2$

$$
\left[
\begin{array}{cc|c}
1 & \frac{3}{2} & 50 \\
0 & 1 & 30
\end{array}
\right]
\;\;\xrightarrow{F_1 = F_1- \frac{3}{2}F_2}\;\;
\left[
\begin{array}{cc|c}
1 & 0 & 5 \\
0 & 1 & 30
\end{array}
\right]
$$

**Solución** 

$$ 
\left[ 
\begin{array}{cc|c}
1 & 0 & 5 \\
0 & 1 & 30
\end{array} 
\right]
\implies
\begin{array}{cc|c}
x=5 \\
y=30
\end{array} 
$$

**Ejemplo 2**

$$
\underbrace{
\begin{align}
5x-8y &= -\frac{64}{16} \\
2x+3y &= \frac{153}{40} \\
\end{align}} 
_{\mathbf{SEL}}
\implies
\underbrace{
\left[ \begin{array}{cc|c}
5 & -8 & -4 \\
2 & 3 & \frac{153}{40}
\end{array} \right]
}
_{\mathbf{Matriz}}
$$


### Ejemplos

A)  

$$
\left[ \begin{array}{cc|c}
2 & 3 & 7 \\
3 & 1 & 7
\end{array} \right]
$$

B)  

$$
\left[ \begin{array}{cc|c}
2 & 4 & 13 \\
-1 & 3 & \frac{17}{2}
\end{array} \right]
$$

C)  

$$
\left[ \begin{array}{cc|c}
1 & \frac{3}{2} & 2 \\
3 & 6 & 7
\end{array} \right]
$$

## Propiedades

### Dimensión

Una matriz $m$x$n$ o $i$x$j$ se dice que es de orden o tamaño $m$x$n$ o $i$x$j$, donde:

-   $m$ / $i$ indican el **número de filas**.
-   $n$ / $j$ indican el **número de columnas**.

Por ejemplo:

$$
A= 
\underbrace{
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}} 
_{\substack{2x2 \\ \text{Matriz cuadrada}}}
\quad
B= \underbrace{
\begin{bmatrix}
-1 & 3 \\
4 & 0 \\
1 & -2
\end{bmatrix}} 
_{3x2} 
\quad
C= \underbrace{
\begin{bmatrix}
-1 & 4 & 1 \\
3 & 0 & 2 
\end{bmatrix}} _{2x3} 
$$

$$
D= \underbrace{
\begin{bmatrix}
1 & 6 & -2 \\
3 & 1 & 4 \\
2 & -6 & 5
\end{bmatrix}} 
_{\substack{3x3 \\ \text{Matriz cuadrada}}} 
\quad
E= \underbrace{
\begin{bmatrix}
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
\end{bmatrix}} 
_{\substack{2x4 \\ \text{Matriz cero}}} 
$$


Dos matrices $A=(a_{ij})$ y $B=(b_{ij})$ son iguales **si y solo si** tienen el mismo orden o tamaño.

### Operaciones con escalares

Sea $A$ una matrix de $m$x$n$ y $\alpha$ un escalar:

1)  $\alpha A$

2)  $1A=A$

3)  $A + \varnothing = A$

$$
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
+ 
\begin{bmatrix}
0 & 0 \\
0 & 0
\end{bmatrix}
=
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
$$

4)  $\varnothing A = \varnothing$

$$
\varnothing
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
= 
\begin{bmatrix}
0 & 0 \\
0 & 0
\end{bmatrix}
$$

### Suma

Dos matrices A y B se pueden sumar **si y solo si** tienen el mismo tamaño. La suma se realiza elemento por elemento, es decir:

$$
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
+ 
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}
=
\begin{bmatrix}
a_{11}+b_{11} & a_{12}+b_{12} \\
a_{21}+b_{21} & a_{22}+b_{22}
\end{bmatrix}
$$

Para la suma de matrices podemos utilizar las siguientes propiedades.

1)  Propiedad conmutativa: $A+B=B+A$

$$
A+B=
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
+ 
\begin{bmatrix}
3 & -1 \\
2 & -4
\end{bmatrix}
=
\begin{bmatrix}
4 & 2 \\
6 & -2
\end{bmatrix}
$$

$$
B+A=
\begin{bmatrix}
3 & -1 \\
2 & -4
\end{bmatrix}
+
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
=
\begin{bmatrix}
4 & 2 \\
6 & -2
\end{bmatrix}
$$

2)  Propiedad asociativa: $(A+B)+C=A+(B+C)$.

$$
(A+B)+C=
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
+
\begin{bmatrix}
3 & -1 \\
2 & -4
\end{bmatrix}
+
\begin{bmatrix}
1 & 2 \\
-3 & -2
\end{bmatrix}
=
\begin{bmatrix}
4 & 2 \\
6 & -2
\end{bmatrix}
+
\begin{bmatrix}
1 & 2 \\
-3 & -2
\end{bmatrix}
=
\begin{bmatrix}
5 & 4 \\
3 & -4
\end{bmatrix}
$$

$$
A+(B+C)=
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
+
\begin{bmatrix}
3 & -1 \\
2 & -4
\end{bmatrix}
+
\begin{bmatrix}
1 & 2 \\
-3 & -2
\end{bmatrix}
=
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
+
\begin{bmatrix}
4 & 1 \\
-1 & -6
\end{bmatrix}
=
\begin{bmatrix}
5 & 4 \\
3 & -4
\end{bmatrix}
$$


3)  Propiedad distributiva: $\alpha(A+B)=\alpha A + \alpha B$.

$$
2(A+B)=
2
\begin{bmatrix}
1 & 3 \\
4 & 2
\end{bmatrix}
+ 
2
\begin{bmatrix}
3 & -1 \\
2 & -4
\end{bmatrix}
=
\begin{bmatrix}
2 & 6 \\
8 & 4
\end{bmatrix}
+
\begin{bmatrix}
6 & -2 \\
4 & -8
\end{bmatrix}
=
\begin{bmatrix}
8 & 4 \\
12 & -4
\end{bmatrix}
$$

#### Ejemplos

A partir de las siguientes matrices, resuelva los ejercicios

$$
A = 
\begin{bmatrix}
1 & 3 \\
2 & 5 \\
-1 & 2
\end{bmatrix}; 
\quad 
B=
\begin{bmatrix}
-2 & 0 \\
1 & 4 \\
-7 & 5
\end{bmatrix};
\quad
C=
\begin{bmatrix}
-1 & 1 \\
4 & 6 \\
-7 & 3
\end{bmatrix}
$$

1)  $3A$
2)  $A+B$
3)  $A-C$
4)  $2C-5A$
5)  $A+B+C$
6)  $\varnothing B$
7)  $-7A+3B$
8)  $C-A-B$
9)  $2A-3B+4C$
10) $7C-3B+2A$
11) $2(A+C)$
12) $2B-2C$

### Multiplicación

Dos matrices, $A_{mn}$ y $B_{ij}$ se pueden multiplicar **si y solo si** $n=i$, es decir, el número de columnas de A es igual al número de filas de B. Por ejemplo


$$
A = 
\underbrace{
\begin{bmatrix}
1 & 8 & 0 \\
-3 & 2 & 5 
\end{bmatrix}}
_{2x3}
; \quad
B=
\underbrace{
\begin{bmatrix}
9 & 0 \\
-6 & 2 \\
8 & 4
\end{bmatrix}}
_{3x2}
$$

-   Fila 1 por columna 1

$$
\begin{pmatrix}
1 & 8 & 0 
\end{pmatrix}
\begin{pmatrix}
9 \\
-6 \\
8 
\end{pmatrix}
=
9-48+0=-39
$$

-   Fila 1 por columna 2

$$
\begin{pmatrix}
1 & 8 & 0 
\end{pmatrix}
\begin{pmatrix}
0 \\
2 \\
4 
\end{pmatrix}
=
0+16+0=16
$$

-   Fila 2 por columna 1

$$
\begin{pmatrix}
-3 & 2 & 5 
\end{pmatrix}
\begin{pmatrix}
9 \\
-6 \\
8 
\end{pmatrix}
=
-27-12+40=1
$$

-   Fila 2 por columna 2

$$
\begin{pmatrix}
-3 & 2 & 5 
\end{pmatrix}
\begin{pmatrix}
0 \\
2 \\
4 
\end{pmatrix}
=
0+4+20=24
$$

Como resultado de multiplicar las matrices A y B tenemos:

$$
C=
\begin{bmatrix}
-39 & 16 \\
1 & 24 
\end{bmatrix}
$$

En la multiplicación de matrices podemos utilizar las siguientes propiedades.

1)  Propiedad distributiva: $A(B+C)=AB+AC$
2)  Propiedad asociativa: $A(BC)=(AB)C$

#### Ejemplos

$$
A =
\begin{bmatrix}
4 & 6 \\
8 & 2 
\end{bmatrix}
\qquad
B=
\begin{bmatrix}
-3 & 9 \\
5 & -7 
\end{bmatrix}
\qquad
C=
\begin{bmatrix}
-9 & 1 & 3 \\
0 & 4 & -8 
\end{bmatrix}
$$

$$
D=
\begin{bmatrix}
7 & 4 \\
6 & -1 \\
-5 & 2
\end{bmatrix}
\qquad
E=
\begin{bmatrix}
1 & 7 & -8 \\
4 & 9 & -7 \\
2 & 0 & 3
\end{bmatrix}
$$


1)  $B+A$
2)  $7D$
3)  $\frac{1}{2}A$
4)  $8(CD)-B$
5)  $(ED)(5C)+A$
6)  $\frac{1}{4}AC$
7)  $(D-(AC))+E$
8)  $3(EC)$
