project:
  type: book
  output-dir: docs
published-title: Última actualización
book:
  title: Taller de Economía Cuantitativa III
  author:
  - name: Eduardo Castro Rabadán
  - name: Marvin Ivan Trejo Mendez
  search: true
  navbar:
    background: '#003366'
    foreground: white
  sidebar:
    style: docked
    background: '#f5f5f5'
  date: today
  date-format: DD/MM/YYYY
  chapters:
  - part: Introducción
    chapters: 
    - index.qmd
  - part: Sistemas de ecuaciones lineales
    chapters:
    - 01_sel.qmd
    - 01_ejercicios.qmd
    - 01_tarea.qmd
  - part: Matrices
    chapters:
    - 02_matrices.qmd
    - 02_tarea.qmd
  - part: Determinantes
    chapters:
    - 03_determinantes.qmd
    # - 03_ejercicios.qmd
    - 03_tarea.qmd
  - part: Inversa
    chapters:
    - 04_inversa.qmd
    - 04_tarea.qmd
    
format:
  html:
    theme: flatly
    css:
    - styles.css
    - include/webex.css
    toc: true
    toc-location: right
    toc-title: Contenido
    number-sections: false
    smooth-scroll: true
    include-after-body: include/webex.js
