project:
  type: book
  output-dir: docs
  
published-title: "Última actualización"

book:
  title: "Taller de Economía Cuantitativa III"
  author: 
    - name: "Eduardo Castro Rabadán"
    - name: "Marvin Ivan Trejo Mendez"
  search: true
  navbar:
    background: "#003366"
    foreground: "white"
  sidebar: 
   style: "docked"
   background: "#f5f5f5"
  date: today
  date-format: "DD/MM/YYYY"
  chapters: 
    - part: "Introducción"
      chapters: 
        - index.qmd
    - part: "Semana 1"
      # chapters: 
      # - 01_vectores.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: right